### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by patrickbeam** [balanced-ops/ec2-cost-tools#3]
After the purchase of RI's the script starts throwing the following error.  

ec2-costs us-east-1
/Users/pbeam/github/ec2-cost-tools/ec2_costs/**main**.py:24: Warning: Click detected the use of the unicode_literals **future** import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  def main(region, show_expirations=False):
Traceback (most recent call last):
  File "/Users/pbeam/github/ec2-cost-tools/venv/bin/ec2-costs", line 9, in <module>
    load_entry_point('ec2-costs==0.1.0', 'console_scripts', 'ec2-costs')()
  File "/Users/pbeam/github/ec2-cost-tools/venv/lib/python2.7/site-packages/click/core.py", line 700, in **call**
    return self.main(_args, *_kwargs)
  File "/Users/pbeam/github/ec2-cost-tools/venv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/pbeam/github/ec2-cost-tools/venv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Users/pbeam/github/ec2-cost-tools/venv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(_args, **kwargs)
  File "/Users/pbeam/github/ec2-cost-tools/ec2_costs/**main**.py", line 43, in main
    result = get_reserved_analysis(conn)
  File "/Users/pbeam/github/ec2-cost-tools/ec2_costs/**init**.py", line 143, in get_reserved_analysis
    covered_price = matched.recurring_charges[0].amount
IndexError: list index out of range

**Comment by tomchiverton** [comment]
Same here.

**Comment by tomchiverton** [comment]
Even changing the if to 
```
if matched & len(matched.recurring_charges) > 0
```
doesn't help, because then 
```
Traceback (most recent call last):
  File "/usr/local/bin/ec2-costs", line 9, in <module>
    load_entry_point('ec2-costs', 'console_scripts', 'ec2-costs')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2229, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2235, in resolve
  File "/home/tchiverton/workspace/ec2-cost-tools/ec2_costs/__init__.py", line 2, in <module>
    import ref
ImportError: No module named ref
```
and
```
$ pip install ref
Downloading/unpacking ref
  Could not find any downloads that satisfy the requirement ref
Cleaning up...
No distributions at all found for ref
Storing debug log for failure in XXXX
```

**Comment by AjeetK** [comment]
The problem is with the python version, if you are using less than python 2.7 than you will get this warning. 
Solution: 
1> Either upgrade your python version to 2.7
2> Use virtualenv using python2.7 and than install this package after activating the virtualenv
